console.log(typeof 3.15)
console.log(typeof "string")
console.log(typeof true)
console.log(typeof null)
console.log(typeof undefined)
console.log(typeof Symbol)
console.log(typeof [])
console.log(typeof {})
console.log(typeof new RegExp)
console.log(typeof new Date)